---
- name: Fedora dev workstation setup
  hosts: localhost
  connection: local

  pre_tasks:
    - name: Include config vars
      include_vars: vars/default.config.yml

  tasks:
    - name: Install all dnf packages
      include_tasks: tasks/dnf_packages.yml
      when: install_dnf_packages

    - name: Install and setup zsh
      include_tasks: tasks/zsh.yml
      when: install_zsh

    - name: Install and setup kitty
      include_tasks: tasks/kitty.yml
      when: install_kitty

    - name: Install and setup Rust
      include_tasks: tasks/rust.yml
      when: install_rust

    - name: Install and setup Docker
      include_tasks: tasks/docker.yml
      when: install_docker

    - name: Install and setup flatpak apps
      include_tasks: tasks/flatpak.yml
      when: install_flatpak_apps

    - name: Install and setup VSCode
      include_tasks: tasks/vscode.yml
      when: install_vscode

    - name: Install and setup VirtualBox
      include_tasks: tasks/virtualbox.yml
      when: install_virtualbox

    - name: Install and setup Dropbox
      include_tasks: tasks/dropbox.yml
      when: install_dropbox
