---
- name: Fedora dev workstation setup
  hosts: localhost
  connection: local

  pre_tasks:
    - name: Include config vars
      include_vars: vars/default.config.yml

  tasks:
    - name: Install all dnf packages
      include_tasks: tasks/dnf_packages.yml
      when: install_dnf_packages

    - name: Install and setup zsh
      include_tasks: tasks/zsh.yml
      when: install_zsh

    - name: Install and setup kitty
      include_tasks: tasks/kitty.yml
      when: install_kitty

    - name: Install and setup Rust
      include_tasks: tasks/rust.yml
      when: install_rust
