---
- name: Setup Docker repository
  shell: >-
    sudo dnf -y install dnf-plugins-core &&
    sudo dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo
  become: true

- name: Install Docker Engine
  shell: sudo dnf install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
  become: true

- name: Start Docker and enable at boot
  shell: sudo systemctl start docker && sudo systemctl enable docker
  become: true
