---
- name: Download dropbox
  get_url:
    url: https://www.dropbox.com/download?dl=packages/fedora/nautilus-dropbox-2024.04.17-1.fc39.x86_64.rpm
    dest: /tmp/nautilus-dropbox-2024.04.17-1.fc39.x86_64.rpm
    mode: "0755"
    force: true

- name: Install dropbox
  yum:
    - name: /tmp/nautilus-dropbox-2024.04.17-1.fc39.x86_64.rpm
    - state: present
  become: true
