---
- name: Download godot 4 with C# support
  get_url:
    url: https://github.com/godotengine/godot/releases/download/4.2.2-stable/Godot_v4.2.2-stable_mono_linux_x86_64.zip
    dest: /tmp/godot.zip
    mode: "0755"
    force: true

- name: Extract godot
  unarchive:
    src: /tmp/godot.zip
    dest: /opt
  become: true

- name: Add godot4 to path
  shell: cd /usr/local/bin && sudo ln -s /opt/Godot_v4.2.2-stable_mono_linux_x86_64/Godot_v4.2.2-stable_mono_linux_x86_64 godot4
  become: true
