---
- name: Install kitty
  dnf:
    name:
      - kitty
      - source-foundry-hack-fonts # Ensure that fonts are installed
    state: present
  become: true

- name: Copy kitty.conf
  copy:
    src: ./files/kitty.conf
    dest: ~/.config/kitty/kitty.conf
    force: no
