---
- name: Install zsh
  dnf:
    name: zsh
    state: present
  become: true

- name: Set zsh as default
  user:
    name: "{{ ansible_facts.user_id}}"
    shell: /usr/bin/zsh
  become: true
  when: zsh_default_shell

- name: Check if oh my zsh is installed
  stat:
    path: ~/.oh-my-zsh
  register: stat_result

- name: Download Oh My Zsh installation script
  get_url:
    url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    dest: /tmp/install_ohmyzsh.sh
  when: not stat_result.stat.exists

- name: Run Oh My Zsh installation script
  command: sh /tmp/install_ohmyzsh.sh --unattended
  register: ohmyzsh_result
  failed_when: "'FAILED' in ohmyzsh_result.stderr"
  when: not stat_result.stat.exists
